# Generated by Django 6.0.4 on 2026-04-08 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_asignatura', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('dni', models.CharField(db_column='DNI', max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=120)),
                ('contrato_hasta', models.DateField(db_column='Contrato_hasta')),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuario',
                'db_table': 'Tipos_usuarios',
            },
        ),
        migrations.CreateModel(
            name='AusenciaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_la_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], db_column='Dia_de_la_semana', max_length=10)),
                ('hora_inicio', models.TimeField(db_column='Hora_inicio')),
                ('hora_fin', models.TimeField(db_column='Hora_fin')),
                ('turno', models.CharField(db_column='Turno', max_length=50)),
                ('tipo_repeticion', models.CharField(db_column='Tipo_repeticion', max_length=50)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('dni', models.ForeignKey(db_column='DNI', on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
            ],
            options={
                'db_table': 'Ausencia_profesor',
                'ordering': ['dia_de_la_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='GradoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(db_column='ID_Asignatura', on_delete=django.db.models.deletion.CASCADE, to='horarios.asignatura')),
                ('grado', models.ForeignKey(db_column='ID_Grado', on_delete=django.db.models.deletion.CASCADE, to='horarios.grado')),
            ],
            options={
                'db_table': 'Grado_Asignatura',
                'unique_together': {('grado', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='AsignaturaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(db_column='ID_Asignatura', on_delete=django.db.models.deletion.CASCADE, to='horarios.asignatura')),
                ('dni', models.ForeignKey(db_column='Dni', on_delete=django.db.models.deletion.CASCADE, to='horarios.profesor')),
            ],
            options={
                'db_table': 'Asignaturas_Profesor',
                'unique_together': {('dni', 'asignatura')},
            },
        ),
    ]
