# Generated by Django 6.0.4 on 2026-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_horarioclase_perfilusuario_solicitudcambioprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='anio',
            field=models.PositiveSmallIntegerField(db_column='Anio', default=1),
        ),
    ]
