# Generated by Django 6.0.4 on 2026-04-08 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_alter_asignatura_tipo_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='anio',
            field=models.PositiveSmallIntegerField(db_column='Anio', default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
