# Generated by Django 6.0.4 on 2026-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_alter_asignatura_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='tipo_asignatura',
            field=models.CharField(choices=[('B', 'B'), ('OB', 'OB'), ('OP', 'OP'), ('TFG', 'TFG')], max_length=3),
        ),
    ]
