# Generated by Django 6.0.4 on 2026-04-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_alter_asignatura_tipo_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='contrato_hasta',
        ),
    ]
