# Generated by Django 6.0.4 on 2026-04-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_remove_profesor_contrato_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='contrato_hasta',
            field=models.DateField(blank=True, db_column='Contrato_hasta', null=True),
        ),
    ]
