# Generated by Django 6.0.4 on 2026-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_profesor_contrato_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='contrato_indefinido',
            field=models.BooleanField(db_column='Contrato_indefinido', default=False),
        ),
    ]
