# Generated by Django 6.0.4 on 2026-04-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0009_profesor_contrato_indefinido'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='cuatrimestre',
            field=models.CharField(choices=[('1', '1º'), ('2', '2º')], db_column='Cuatrimestre', default='1', max_length=1),
        ),
    ]
