# Generated by Django 6.0.4 on 2026-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0010_asignatura_cuatrimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradoasignatura',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('IS', 'Ingeniería del Software'), ('TI', 'Tecnologías de la Información')], db_column='Especialidad', max_length=2, null=True),
        ),
    ]
